version: '3.4'

# This is an example docker-compose file to quickly test an IPFS Cluster
# with multiple peers on a contained environment.

# It runs 3 cluster peers (cluster0, cluster1...) attached to go-ipfs daemons
# (ipfs0, ipfs1...) using the CRDT consensus component. Cluster peers
# autodiscover themselves using mDNS on the docker internal network.
#
# To interact with the cluster use "ipfs-cluster-ctl" (the cluster0 API port is
# exposed to the locahost. You can also "docker exec -ti cluster0 sh" and run
# it from the container. "ipfs-cluster-ctl peers ls" should show all 3 peers a few
# seconds after start.
#
# For persistance, a "compose" folder is created and used to store configurations
# and states. This can be used to edit configurations in subsequent runs. It looks
# as follows:
#
# compose/
# |-- cluster0
# |-- cluster1
# |-- ...
# |-- ipfs0
# |-- ipfs1
# |-- ...
# 
# During the first start, default configurations are created for all peers.

services:

##################################################################################
## Database & DB API #############################################################
##################################################################################

  rest:
    image: postgrest/postgrest:v8.0.0
    depends_on:
      - db
    restart: always
    ports:
      - 3000:3000/tcp
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  db:
    build:
      context: ./postgres
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432


  postgrest-tunnel:
    environment:
      PORT: "3000"
      LOCAL_HOST: "rest"
      SUBDOMAIN: "${USER}-postgrest-${DEV_CLUSTER_PROJECT:-nft-storage}" 
    depends_on:
      - rest
    build:
      context: ./localtunnel


##################################################################################
## Cluster PEER 0 ################################################################
##################################################################################

  ipfs0:
    image: ipfs/go-ipfs:latest
#   ports:
#     - "4001:4001" # ipfs swarm - expose if needed/wanted
#     - "5001:5001" # ipfs api - expose if needed/wanted
#     - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./cluster-data/ipfs0:/data/ipfs
      
  cluster0:
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_IPFSPROXY_LISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9095
    ports:
          # Open API port (allows ipfs-cluster-ctl usage on host)
          - "0.0.0.0:9094:9094"
          - "0.0.0.0:9095:9095"
          # The cluster swarm port would need  to be exposed if this container
          # was to connect to cluster peers on other hosts.
          # But this is just a testing cluster.
          # - "9096:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./cluster-data/cluster0:/data/ipfs-cluster

  cluster-api-tunnel:
    environment:
      PORT: "9094"
      LOCAL_HOST: "cluster0"
      SUBDOMAIN: "${USER}-cluster-api-${DEV_CLUSTER_PROJECT:-nft-storage}"
    depends_on:
      - cluster0
    build:
      context: ./localtunnel

  ipfs-api-proxy-tunnel:
    environment:
      PORT: "9095"
      LOCAL_HOST: "cluster0"
      SUBDOMAIN: "${USER}-ipfs-proxy-api-${DEV_CLUSTER_PROJECT:-nft-storage}" 
    depends_on:
      - cluster0
    build:
      context: ./localtunnel
